name: "Windows 7 x64"
on:
  push:
    branches:
      - windows7
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: 'Git Clone'
        shell: cmd
        run: |
          mkdir C:\onnxruntime
          git clone -b windows7 --depth 1 --single-branch https://github.com/xzmzm/onnxruntime.git C:\onnxruntime
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - run: Get-PSDrive
      # - name: 'Delete .git'
        # shell: cmd
        # run: |
          # rmdir /s /q ${{ github.workspace }}\.git
      - name: 'Build and Test'
        working-directory: C:\onnxruntime
        run: |
          python C:/onnxruntime/tools/ci_build/build.py --build_dir C:\onnxruntime\build\windows_x64 --update --build --build_java --skip_tests --enable_msvc_static_runtime --build_shared_lib --ms_experimental --cmake_generator "Visual Studio 16 2019" --config Release --compile_no_warning_as_error --enable_lto --disable_rtti --cmake_extra_defines CMAKE_SYSTEM_VERSION=10.0.19041.0 --cmake_extra_defines onnxruntime_USE_AVX=ON --cmake_extra_defines onnxruntime_USE_AVX2=ON
      - name: 'Upload Release Files'
        uses: actions/upload-artifact@v3
        with:
          name: release_files_x64
          path: |
            C:\onnxruntime\build\windows_x64\Release\Release
            !C:\onnxruntime\build\windows_x64\Release\Release\onnxruntime_providers.lib
            !C:\onnxruntime\build\windows_x64\Release\Release\onnxruntime_optimizer.lib
            !C:\onnxruntime\build\windows_x64\Release\Release\onnxruntime_framework.lib            
            !C:\onnxruntime\build\windows_x64\Release\Release\onnxruntime_session.lib                        
